apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vote
spec:
  replicas: 6
  template:
    metadata:
      labels:
        app: vote
        version: v1
    spec:
      containers:
      - image: dockersamples/examplevotingapp_vote:after
        name: vote
