apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/tls-acme: "true"
spec:
  tls:
    - hosts:
      - rp-aks-centralus-api-ingress.centralus.cloudapp.azure.com
      secretName: rp-aks-centralus-api-ingress-tls
  rules:
  - host: rp-aks-centralus-api-ingress.centralus.cloudapp.azure.com
    http:
      paths:
      - path: /api-a
        backend:
          serviceName: api-a
          servicePort: 80
      - path: /api-b
        backend:
          serviceName: api-b
          servicePort: 80